### ISSUE TITLE
Add HTTP library

### ISSUE THREAD

**Issue by gabriel-laet** [doubleleft/hook-android#4]
Add a consistent HTTP library for handling background tasks, multipart requests, multiple requests, etc. The current solution we have for making HTTP requests it's too simple (something like AFNetworking for Android).

The [Request.java](https://github.com/doubleleft/dl-api-android/blob/master/lib/dlapi/src/main/java/com/doubleleft/api/Request.java) class should make requests using a better library.

**Comment by endel** [comment]
We're now using [android-async-http](https://github.com/loopj/android-async-http) :smile:
